// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {environment} from '../models';
import {workspace} from '../models';
import {main} from '../models';

export function CreateCollection(arg1:collection.CreateCollectionRequest):Promise<collection.CollectionResponse>;

export function CreateEnvironment(arg1:environment.CreateEnvironmentRequest):Promise<environment.EnvironmentResponse>;

export function CreateFolder(arg1:collection.CreateFolderRequest):Promise<collection.FolderResponse>;

export function CreateRequest(arg1:collection.CreateRequestRequest):Promise<collection.RequestResponse>;

export function CreateWorkspace(arg1:workspace.CreateWorkspaceRequest):Promise<workspace.WorkspaceResponse>;

export function DeleteCollection(arg1:string,arg2:string):Promise<void>;

export function DeleteEnvironment(arg1:string,arg2:string):Promise<void>;

export function DeleteFolder(arg1:string,arg2:string):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteWorkspace(arg1:string,arg2:string):Promise<void>;

export function DuplicateCollection(arg1:string):Promise<collection.CollectionResponse>;

export function DuplicateEnvironment(arg1:string):Promise<environment.EnvironmentResponse>;

export function DuplicateFolder(arg1:string):Promise<collection.FolderResponse>;

export function DuplicateRequest(arg1:string):Promise<collection.RequestResponse>;

export function GetCollection(arg1:string):Promise<collection.CollectionResponse>;

export function GetRequest(arg1:string):Promise<collection.RequestResponse>;

export function GetWorkspace(arg1:string):Promise<workspace.WorkspaceResponse>;

export function ListCollections(arg1:string):Promise<Array<collection.CollectionResponse>>;

export function ListEnvironments(arg1:string):Promise<Array<environment.EnvironmentResponse>>;

export function ListWorkspaces():Promise<Array<workspace.WorkspaceResponse>>;

export function MoveCollection(arg1:string,arg2:collection.MoveCollectionRequest):Promise<collection.CollectionResponse>;

export function RenameCollection(arg1:string,arg2:string):Promise<collection.CollectionResponse>;

export function RenameFolder(arg1:string,arg2:collection.RenameFolderRequest):Promise<collection.FolderResponse>;

export function RenameRequest(arg1:string,arg2:collection.RenameRequestRequest):Promise<collection.RequestResponse>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<workspace.WorkspaceResponse>;

export function ReorderCollectionItems(arg1:string,arg2:string,arg3:collection.ReorderItemsRequest):Promise<void>;

export function SendRequest(arg1:main.ProxyPayload):Promise<main.ProxyResponse>;

export function UpdateCollectionFavorite(arg1:string,arg2:boolean):Promise<collection.CollectionResponse>;

export function UpdateCollectionSortOrder(arg1:string,arg2:string,arg3:string):Promise<collection.CollectionResponse>;

export function UpdateEnvironment(arg1:string,arg2:environment.UpdateEnvironmentRequest):Promise<environment.EnvironmentResponse>;

export function UpdateFolderSortOrder(arg1:string,arg2:string,arg3:string):Promise<collection.FolderResponse>;

export function UpdateRequest(arg1:string,arg2:collection.UpdateRequestRequest):Promise<collection.RequestResponse>;
