// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';

export function CreateWorkspace(arg1:workspace.CreateWorkspaceRequest):Promise<workspace.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetWorkspace(arg1:string):Promise<workspace.Workspace>;

export function ListWorkspaces():Promise<Array<workspace.Workspace>>;

export function UpdateWorkspace(arg1:string,arg2:workspace.CreateWorkspaceRequest):Promise<workspace.Workspace>;
