// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {workspace} from '../models';

export function CreateCollection(arg1:collection.CreateCollectionRequest):Promise<collection.CollectionResponse>;

export function CreateWorkspace(arg1:workspace.CreateWorkspaceRequest):Promise<workspace.WorkspaceResponse>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DuplicateCollection(arg1:string):Promise<collection.CollectionResponse>;

export function GetWorkspace(arg1:string):Promise<workspace.WorkspaceResponse>;

export function ListCollections(arg1:string):Promise<Array<collection.CollectionResponse>>;

export function ListWorkspaces():Promise<Array<workspace.WorkspaceResponse>>;

export function MoveCollection(arg1:string,arg2:collection.MoveCollectionRequest):Promise<collection.CollectionResponse>;

export function RenameCollection(arg1:string,arg2:string):Promise<collection.CollectionResponse>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<workspace.WorkspaceResponse>;

export function UpdateCollectionFavorite(arg1:string,arg2:boolean):Promise<collection.CollectionResponse>;
