// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['main']['App']['CreateEnvironment'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateRequest(arg1) {
  return window['go']['main']['App']['CreateRequest'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteCollection(arg1, arg2) {
  return window['go']['main']['App']['DeleteCollection'](arg1, arg2);
}

export function DeleteEnvironment(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1, arg2);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2, arg3);
}

export function DeleteWorkspace(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1, arg2);
}

export function DuplicateCollection(arg1) {
  return window['go']['main']['App']['DuplicateCollection'](arg1);
}

export function DuplicateEnvironment(arg1) {
  return window['go']['main']['App']['DuplicateEnvironment'](arg1);
}

export function DuplicateFolder(arg1) {
  return window['go']['main']['App']['DuplicateFolder'](arg1);
}

export function DuplicateRequest(arg1) {
  return window['go']['main']['App']['DuplicateRequest'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function ListCollections(arg1) {
  return window['go']['main']['App']['ListCollections'](arg1);
}

export function ListEnvironments(arg1) {
  return window['go']['main']['App']['ListEnvironments'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function MoveCollection(arg1, arg2) {
  return window['go']['main']['App']['MoveCollection'](arg1, arg2);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RenameRequest(arg1, arg2) {
  return window['go']['main']['App']['RenameRequest'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function ReorderCollectionItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderCollectionItems'](arg1, arg2, arg3);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function UpdateCollectionFavorite(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionFavorite'](arg1, arg2);
}

export function UpdateCollectionSortOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCollectionSortOrder'](arg1, arg2, arg3);
}

export function UpdateEnvironment(arg1, arg2) {
  return window['go']['main']['App']['UpdateEnvironment'](arg1, arg2);
}

export function UpdateFolderSortOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFolderSortOrder'](arg1, arg2, arg3);
}

export function UpdateRequest(arg1, arg2) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2);
}
