// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DuplicateCollection(arg1) {
  return window['go']['main']['App']['DuplicateCollection'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function ListCollections(arg1) {
  return window['go']['main']['App']['ListCollections'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function MoveCollection(arg1, arg2) {
  return window['go']['main']['App']['MoveCollection'](arg1, arg2);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function UpdateCollectionFavorite(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionFavorite'](arg1, arg2);
}
